version: '3'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: hubspot-jb
    image: jonathanbach/hubspot-jb
    build: .
    env_file: .env
    ports:
      - "3000:3000"